containerPort: 3000
health:
  path: /api/health
ingress:
  enabled: false
runAsUser: 101
runAsGroup: 101
minReplicaCount: 1
autoscaling:
  enabled: false
deployStrategy:
  rollingUpdate:
    maxUnavailable: 50%
  type: RollingUpdate